name = "MakieDraw"
uuid = "8315f7d3-d5d2-4d16-bebe-3aa4ef51e4f8"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.2.1"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
GeometryBasics = "0.4, 0.5, 0.6"
Makie = "0.20"
Tables = "1"
julia = "1.6"

[extras]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GeoInterface", "GeoJSON", "Test"]
