name = "MakieDraw"
uuid = "8315f7d3-d5d2-4d16-bebe-3aa4ef51e4f8"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
